version: '2'
services:
  backend:
    container_name: kloster_backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    env_file: .env
    ports:
      - '8000:8000'
  nginx:
    container_name: kloster_nginx
    build:
      context: ./web
      dockerfile: ./build/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./web/app:/var/www/kloster/:rw
      - ./nginx-conf-dev:/etc/nginx/conf.d/:ro


