version: '2'
services:
  backend:
    container_name: kloster_backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    env_file: .env
    user: '1000'
    ports:
      - '81:8000'

