version: '2'
services:
  backend:
    container_name: kloster_backend
    restart: always
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    env_file: .env
    ports:
      - '8000:8000'

